### ISSUE TITLE
TypeError: EventEmitter is not a constructor at new Stripe

### ISSUE THREAD

**Issue by Sananes** [wobsoriano/solid-stripe#1]
@wobsoriano First of all, thank you for this library! I'm getting the following error though and I'm not too sure why?

Maybe you can help me:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/1671973/193015491-d80e3db7-c1ab-43bd-ab48-7a88287ed7f9.png">

I have a feeling its to do with the server function not running on the server.
`~/utils/create-payment-intent.ts`

```
import Stripe from 'stripe'

const stripe = new Stripe(import.meta.env.VITE_STRIPE_SECRET_KEY, {
  apiVersion: '2022-08-01',
})

export default function createPaymentIntent() {
  return stripe.paymentIntents.create({
    amount: 1069,
    currency: 'eur',
    automatic_payment_methods: { enabled: true },
  })
}
```

Have you ran into this issue before?

Thanks in advance!

**Comment by wobsoriano** [comment]
Hey, can you try the latest release? Thanks!
