### ISSUE TITLE
<Card> gone in .7?

### ISSUE THREAD

**Issue by timothyallan** [wobsoriano/solid-stripe#17]
Hey there, just updated from .4 to .7 and it looks like `<Card/>` is gone now? 

Not sure which release it was removed in after .4 as it's not mentioned at all in any of the releases, so I'm wondering if there's somewhere else to import it, or if we need to replace it, what the best approach to replace it is? Thanks!

**Comment by wobsoriano** [comment]
You can see all elements here https://github.com/wobsoriano/solid-stripe/blob/main/src/index.tsx

**Comment by timothyallan** [comment]
Perfect! Easy to update... Thanks for the library, it works great :)
