### ISSUE TITLE
IntegrationError: You must pass in a clientSecret when calling stripe.confirmPayment()

### ISSUE THREAD

**Issue by RATIU5** [wobsoriano/solid-stripe#18]
Using the example that was provided, I received the following error upon checkout.
```
IntegrationError: You must pass in a clientSecret when calling stripe.confirmPayment().
```
I logged the result of my client secret, and it logged successfully. I even tried hard-coding in the client secret value, and I still get the error.

Refer to the example in the README for the code. The versions that I'm using:
```json
"@stripe/stripe-js": "^4.9.0",
"solid-js": "^1.9.3",
"solid-stripe": "^0.7.0",
"stripe": "^17.3.1",
```

**Comment by wobsoriano** [comment]
thanks for reporting, Ill take a look asap

**Comment by RATIU5** [comment]
Thanks! I tried implementing elements using plain JS/HTML and it worked fine. Also for more information, I'm using Astro for SSR and astro islands. Not sure if that has any effect on this.

**Comment by RATIU5** [comment]
Update: I think this may be an issue on my end on how I setup my backend logic. I believe I'm passing in the wrong type of secret. I will try to get it working with this in mind. I will also update here if it fails.

**Comment by wobsoriano** [comment]
Feel free to reopen!
