### ISSUE TITLE
Can't set some properties on address element

### ISSUE THREAD

**Issue by chxry** [wobsoriano/solid-stripe#6]
When creating an address element like this, the `allowedCountries` and `fields` properties are ignored.
```<Address mode="shipping" allowedCountries={["uk"]} fields={{ phone: "always" }} />```

**Comment by wobsoriano** [comment]
Hi! Can you update to latest version? You should now be doing it like this:

```tsx
import { AddressElement  } from 'solid-stripe'

<AddressElement options={{ mode: 'shipping', allowedCountries: ['uk'], fields: { phone: 'always' } }} />
```

All props should now be in the `options` prop 🫡
